# config.yaml
openai_model: "gpt-3.5-turbo"
embedding_model_id: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
csv_loader_settings:
  delimiter: ','
  quotechar: '"'
  fieldnames: ['Oficina', 'Nombre', 'Descripcion', 'Telefono']
